name: bureaucrat branch

on: [pull_request]

env:
  BUNDLER_ACCESS_TOKEN: ${{ secrets.TECH_OPS_ACCESS_TOKEN }}
  BUNDLE_RUBYGEMS__PKG__GITHUB__COM: ${{ secrets.TECH_OPS_ACCESS_TOKEN }}

jobs:
  build:
    name: Test + Build + Publish
    runs-on: ubuntu-20.04

    services:
      redis:
        image: redis:4-alpine
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Tests
        run: make setup

      - name: Test
        run: make test

      - name: Publish to GPR
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: Bearer ${{ secrets.GITHUB_TOKEN }}\n" > $HOME/.gem/credentials
          SC_PRERELEASE=true gem build *.gemspec
          gem push -v --KEY github --host https://rubygems.pkg.github.com/sittercity *.gem
